@startuml

class ConfigurationDb
class ConfigurationDao
class ConfigurationRepository {
  +isLoaded(): boolean
}
ConfigurationRepository -down-> ConfigurationDao
ConfigurationDao -down-> ConfigurationDb

@enduml